# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/PartitionCheckII/PartitionCheckII.srcs/sources_1/bd/PartitionCheckII/ip/PartitionCheckII_PartitionCheckII_0_4/PartitionCheckII_PartitionCheckII_0_4.xci
# IP: The module: 'PartitionCheckII_PartitionCheckII_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/PartitionCheckII/PartitionCheckII.srcs/sources_1/bd/PartitionCheckII/ip/PartitionCheckII_PartitionCheckII_0_4/constraints/PartitionCheckII_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PartitionCheckII_PartitionCheckII_0_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado/PartitionCheckII/PartitionCheckII.srcs/sources_1/bd/PartitionCheckII/ip/PartitionCheckII_PartitionCheckII_0_4/PartitionCheckII_PartitionCheckII_0_4.xci
# IP: The module: 'PartitionCheckII_PartitionCheckII_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/PartitionCheckII/PartitionCheckII.srcs/sources_1/bd/PartitionCheckII/ip/PartitionCheckII_PartitionCheckII_0_4/constraints/PartitionCheckII_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PartitionCheckII_PartitionCheckII_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
