# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/PartitionCheckII/PartitionCheckII.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PartitionCheckII || ORIG_REF_NAME==PartitionCheckII} -quiet] -quiet

# IP: bd/PartitionCheckII/ip/PartitionCheckII_processing_system7_0_0/PartitionCheckII_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PartitionCheckII_processing_system7_0_0 || ORIG_REF_NAME==PartitionCheckII_processing_system7_0_0} -quiet] -quiet

# IP: bd/PartitionCheckII/ip/PartitionCheckII_PartitionCheckII_0_4/PartitionCheckII_PartitionCheckII_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PartitionCheckII_PartitionCheckII_0_4 || ORIG_REF_NAME==PartitionCheckII_PartitionCheckII_0_4} -quiet] -quiet

# IP: bd/PartitionCheckII/ip/PartitionCheckII_ps7_0_axi_periph_4/PartitionCheckII_ps7_0_axi_periph_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PartitionCheckII_ps7_0_axi_periph_4 || ORIG_REF_NAME==PartitionCheckII_ps7_0_axi_periph_4} -quiet] -quiet

# IP: bd/PartitionCheckII/ip/PartitionCheckII_rst_ps7_0_50M_4/PartitionCheckII_rst_ps7_0_50M_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PartitionCheckII_rst_ps7_0_50M_4 || ORIG_REF_NAME==PartitionCheckII_rst_ps7_0_50M_4} -quiet] -quiet

# IP: bd/PartitionCheckII/ip/PartitionCheckII_axi_mem_intercon_4/PartitionCheckII_axi_mem_intercon_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PartitionCheckII_axi_mem_intercon_4 || ORIG_REF_NAME==PartitionCheckII_axi_mem_intercon_4} -quiet] -quiet

# IP: bd/PartitionCheckII/ip/PartitionCheckII_auto_pc_6/PartitionCheckII_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PartitionCheckII_auto_pc_6 || ORIG_REF_NAME==PartitionCheckII_auto_pc_6} -quiet] -quiet

# IP: bd/PartitionCheckII/ip/PartitionCheckII_auto_pc_7/PartitionCheckII_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PartitionCheckII_auto_pc_7 || ORIG_REF_NAME==PartitionCheckII_auto_pc_7} -quiet] -quiet

# IP: bd/PartitionCheckII/ip/PartitionCheckII_auto_us_3/PartitionCheckII_auto_us_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PartitionCheckII_auto_us_3 || ORIG_REF_NAME==PartitionCheckII_auto_us_3} -quiet] -quiet

# XDC: bd/PartitionCheckII/PartitionCheckII_ooc.xdc
