# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado/AxiBurst/AxiBurst.srcs/sources_1/bd/AxiBurst/ip/AxiBurst_AxiBurst_0_10/AxiBurst_AxiBurst_0_10.xci
# IP: The module: 'AxiBurst_AxiBurst_0_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/AxiBurst/AxiBurst.srcs/sources_1/bd/AxiBurst/ip/AxiBurst_AxiBurst_0_10/constraints/AxiBurst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AxiBurst_AxiBurst_0_10'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Vivado/AxiBurst/AxiBurst.srcs/sources_1/bd/AxiBurst/ip/AxiBurst_AxiBurst_0_10/AxiBurst_AxiBurst_0_10.xci
# IP: The module: 'AxiBurst_AxiBurst_0_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/AxiBurst/AxiBurst.srcs/sources_1/bd/AxiBurst/ip/AxiBurst_AxiBurst_0_10/constraints/AxiBurst_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AxiBurst_AxiBurst_0_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
