// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="PartitionCheckII,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=1184,HLS_SYN_LUT=1577,HLS_VERSION=2020_1}" *)

module PartitionCheckII (
        ap_clk,
        ap_rst_n,
        m_axi_output_r_AWVALID,
        m_axi_output_r_AWREADY,
        m_axi_output_r_AWADDR,
        m_axi_output_r_AWID,
        m_axi_output_r_AWLEN,
        m_axi_output_r_AWSIZE,
        m_axi_output_r_AWBURST,
        m_axi_output_r_AWLOCK,
        m_axi_output_r_AWCACHE,
        m_axi_output_r_AWPROT,
        m_axi_output_r_AWQOS,
        m_axi_output_r_AWREGION,
        m_axi_output_r_AWUSER,
        m_axi_output_r_WVALID,
        m_axi_output_r_WREADY,
        m_axi_output_r_WDATA,
        m_axi_output_r_WSTRB,
        m_axi_output_r_WLAST,
        m_axi_output_r_WID,
        m_axi_output_r_WUSER,
        m_axi_output_r_ARVALID,
        m_axi_output_r_ARREADY,
        m_axi_output_r_ARADDR,
        m_axi_output_r_ARID,
        m_axi_output_r_ARLEN,
        m_axi_output_r_ARSIZE,
        m_axi_output_r_ARBURST,
        m_axi_output_r_ARLOCK,
        m_axi_output_r_ARCACHE,
        m_axi_output_r_ARPROT,
        m_axi_output_r_ARQOS,
        m_axi_output_r_ARREGION,
        m_axi_output_r_ARUSER,
        m_axi_output_r_RVALID,
        m_axi_output_r_RREADY,
        m_axi_output_r_RDATA,
        m_axi_output_r_RLAST,
        m_axi_output_r_RID,
        m_axi_output_r_RUSER,
        m_axi_output_r_RRESP,
        m_axi_output_r_BVALID,
        m_axi_output_r_BREADY,
        m_axi_output_r_BRESP,
        m_axi_output_r_BID,
        m_axi_output_r_BUSER,
        s_axi_sqrt_AWVALID,
        s_axi_sqrt_AWREADY,
        s_axi_sqrt_AWADDR,
        s_axi_sqrt_WVALID,
        s_axi_sqrt_WREADY,
        s_axi_sqrt_WDATA,
        s_axi_sqrt_WSTRB,
        s_axi_sqrt_ARVALID,
        s_axi_sqrt_ARREADY,
        s_axi_sqrt_ARADDR,
        s_axi_sqrt_RVALID,
        s_axi_sqrt_RREADY,
        s_axi_sqrt_RDATA,
        s_axi_sqrt_RRESP,
        s_axi_sqrt_BVALID,
        s_axi_sqrt_BREADY,
        s_axi_sqrt_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_state5 = 24'd16;
parameter    ap_ST_fsm_state6 = 24'd32;
parameter    ap_ST_fsm_state7 = 24'd64;
parameter    ap_ST_fsm_state8 = 24'd128;
parameter    ap_ST_fsm_state9 = 24'd256;
parameter    ap_ST_fsm_state10 = 24'd512;
parameter    ap_ST_fsm_state11 = 24'd1024;
parameter    ap_ST_fsm_state12 = 24'd2048;
parameter    ap_ST_fsm_state13 = 24'd4096;
parameter    ap_ST_fsm_state14 = 24'd8192;
parameter    ap_ST_fsm_state15 = 24'd16384;
parameter    ap_ST_fsm_state16 = 24'd32768;
parameter    ap_ST_fsm_state17 = 24'd65536;
parameter    ap_ST_fsm_pp0_stage0 = 24'd131072;
parameter    ap_ST_fsm_state21 = 24'd262144;
parameter    ap_ST_fsm_state22 = 24'd524288;
parameter    ap_ST_fsm_state23 = 24'd1048576;
parameter    ap_ST_fsm_state24 = 24'd2097152;
parameter    ap_ST_fsm_pp2_stage0 = 24'd4194304;
parameter    ap_ST_fsm_state27 = 24'd8388608;
parameter    C_S_AXI_SQRT_DATA_WIDTH = 32;
parameter    C_S_AXI_SQRT_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_OUTPUT_R_ID_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_ADDR_WIDTH = 32;
parameter    C_M_AXI_OUTPUT_R_DATA_WIDTH = 32;
parameter    C_M_AXI_OUTPUT_R_AWUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_ARUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_WUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_RUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_BUSER_WIDTH = 1;
parameter    C_M_AXI_OUTPUT_R_USER_VALUE = 0;
parameter    C_M_AXI_OUTPUT_R_PROT_VALUE = 0;
parameter    C_M_AXI_OUTPUT_R_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_SQRT_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_OUTPUT_R_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_output_r_AWVALID;
input   m_axi_output_r_AWREADY;
output  [C_M_AXI_OUTPUT_R_ADDR_WIDTH - 1:0] m_axi_output_r_AWADDR;
output  [C_M_AXI_OUTPUT_R_ID_WIDTH - 1:0] m_axi_output_r_AWID;
output  [7:0] m_axi_output_r_AWLEN;
output  [2:0] m_axi_output_r_AWSIZE;
output  [1:0] m_axi_output_r_AWBURST;
output  [1:0] m_axi_output_r_AWLOCK;
output  [3:0] m_axi_output_r_AWCACHE;
output  [2:0] m_axi_output_r_AWPROT;
output  [3:0] m_axi_output_r_AWQOS;
output  [3:0] m_axi_output_r_AWREGION;
output  [C_M_AXI_OUTPUT_R_AWUSER_WIDTH - 1:0] m_axi_output_r_AWUSER;
output   m_axi_output_r_WVALID;
input   m_axi_output_r_WREADY;
output  [C_M_AXI_OUTPUT_R_DATA_WIDTH - 1:0] m_axi_output_r_WDATA;
output  [C_M_AXI_OUTPUT_R_WSTRB_WIDTH - 1:0] m_axi_output_r_WSTRB;
output   m_axi_output_r_WLAST;
output  [C_M_AXI_OUTPUT_R_ID_WIDTH - 1:0] m_axi_output_r_WID;
output  [C_M_AXI_OUTPUT_R_WUSER_WIDTH - 1:0] m_axi_output_r_WUSER;
output   m_axi_output_r_ARVALID;
input   m_axi_output_r_ARREADY;
output  [C_M_AXI_OUTPUT_R_ADDR_WIDTH - 1:0] m_axi_output_r_ARADDR;
output  [C_M_AXI_OUTPUT_R_ID_WIDTH - 1:0] m_axi_output_r_ARID;
output  [7:0] m_axi_output_r_ARLEN;
output  [2:0] m_axi_output_r_ARSIZE;
output  [1:0] m_axi_output_r_ARBURST;
output  [1:0] m_axi_output_r_ARLOCK;
output  [3:0] m_axi_output_r_ARCACHE;
output  [2:0] m_axi_output_r_ARPROT;
output  [3:0] m_axi_output_r_ARQOS;
output  [3:0] m_axi_output_r_ARREGION;
output  [C_M_AXI_OUTPUT_R_ARUSER_WIDTH - 1:0] m_axi_output_r_ARUSER;
input   m_axi_output_r_RVALID;
output   m_axi_output_r_RREADY;
input  [C_M_AXI_OUTPUT_R_DATA_WIDTH - 1:0] m_axi_output_r_RDATA;
input   m_axi_output_r_RLAST;
input  [C_M_AXI_OUTPUT_R_ID_WIDTH - 1:0] m_axi_output_r_RID;
input  [C_M_AXI_OUTPUT_R_RUSER_WIDTH - 1:0] m_axi_output_r_RUSER;
input  [1:0] m_axi_output_r_RRESP;
input   m_axi_output_r_BVALID;
output   m_axi_output_r_BREADY;
input  [1:0] m_axi_output_r_BRESP;
input  [C_M_AXI_OUTPUT_R_ID_WIDTH - 1:0] m_axi_output_r_BID;
input  [C_M_AXI_OUTPUT_R_BUSER_WIDTH - 1:0] m_axi_output_r_BUSER;
input   s_axi_sqrt_AWVALID;
output   s_axi_sqrt_AWREADY;
input  [C_S_AXI_SQRT_ADDR_WIDTH - 1:0] s_axi_sqrt_AWADDR;
input   s_axi_sqrt_WVALID;
output   s_axi_sqrt_WREADY;
input  [C_S_AXI_SQRT_DATA_WIDTH - 1:0] s_axi_sqrt_WDATA;
input  [C_S_AXI_SQRT_WSTRB_WIDTH - 1:0] s_axi_sqrt_WSTRB;
input   s_axi_sqrt_ARVALID;
output   s_axi_sqrt_ARREADY;
input  [C_S_AXI_SQRT_ADDR_WIDTH - 1:0] s_axi_sqrt_ARADDR;
output   s_axi_sqrt_RVALID;
input   s_axi_sqrt_RREADY;
output  [C_S_AXI_SQRT_DATA_WIDTH - 1:0] s_axi_sqrt_RDATA;
output  [1:0] s_axi_sqrt_RRESP;
output   s_axi_sqrt_BVALID;
input   s_axi_sqrt_BREADY;
output  [1:0] s_axi_sqrt_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] array_r;
wire   [31:0] ap_return;
reg    output_r_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    output_r_blk_n_R;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln21_reg_433;
wire    output_r_AWREADY;
wire    output_r_WREADY;
reg    output_r_ARVALID;
wire    output_r_ARREADY;
reg   [31:0] output_r_ARADDR;
reg   [31:0] output_r_ARLEN;
wire    output_r_RVALID;
reg    output_r_RREADY;
wire   [31:0] output_r_RDATA;
wire    output_r_RLAST;
wire   [0:0] output_r_RID;
wire   [0:0] output_r_RUSER;
wire   [1:0] output_r_RRESP;
wire    output_r_BVALID;
wire   [1:0] output_r_BRESP;
wire   [0:0] output_r_BID;
wire   [0:0] output_r_BUSER;
reg   [29:0] phi_ln21_reg_121;
reg   [29:0] phi_ln21_reg_121_pp0_iter1_reg;
wire    ap_block_state18_pp0_stage0_iter0;
reg    ap_block_state19_pp0_stage0_iter1;
wire    ap_block_state20_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [31:0] sum0s_0_i_reg_168;
reg   [31:0] sum1s_0_i_reg_180;
reg   [31:0] mask_0_i_reg_192;
reg  signed [31:0] i_0_i_reg_203;
reg   [29:0] array1_reg_404;
reg   [31:0] output_addr_reg_409;
reg   [31:0] n_reg_415;
reg   [29:0] lshr_ln_reg_422;
wire    ap_CS_fsm_state10;
wire   [31:0] zext_ln21_1_fu_267_p1;
wire   [0:0] icmp_ln21_fu_271_p2;
reg   [0:0] icmp_ln21_reg_433_pp0_iter1_reg;
wire   [29:0] add_ln21_1_fu_276_p2;
reg   [29:0] add_ln21_1_reg_437;
reg    ap_enable_reg_pp0_iter0;
reg   [31:0] output_addr_read_reg_442;
wire   [31:0] i_fu_292_p2;
wire    ap_CS_fsm_state22;
wire   [31:0] nPartitions_2_fu_298_p2;
wire   [0:0] icmp_ln23_fu_287_p2;
wire   [31:0] nPartitions_1_fu_314_p1;
reg   [31:0] nPartitions_1_reg_460;
wire    ap_CS_fsm_state23;
wire   [31:0] add_ln57_fu_318_p2;
reg   [31:0] add_ln57_reg_465;
wire   [0:0] icmp_ln32_fu_323_p2;
reg   [0:0] icmp_ln32_reg_470;
wire    ap_CS_fsm_state24;
wire   [0:0] icmp_ln57_fu_328_p2;
reg   [0:0] icmp_ln57_reg_474;
wire    ap_CS_fsm_pp2_stage0;
wire    ap_block_state25_pp2_stage0_iter0;
wire    ap_block_state26_pp2_stage0_iter1;
wire    ap_block_pp2_stage0_11001;
wire   [0:0] icmp_ln59_fu_339_p2;
reg   [0:0] icmp_ln59_reg_478;
wire   [31:0] mask_fu_350_p2;
reg    ap_enable_reg_pp2_iter0;
wire   [31:0] i_1_fu_356_p2;
wire   [31:0] sum0s_1_fu_374_p3;
reg    ap_enable_reg_pp2_iter1;
wire   [31:0] sum1s_1_fu_381_p3;
wire   [31:0] i_2_fu_394_p2;
wire    ap_CS_fsm_state27;
wire   [0:0] icmp_ln68_fu_388_p2;
wire    ap_CS_fsm_state17;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state18;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state25;
reg   [6:0] buff_address0;
reg    buff_ce0;
reg    buff_we0;
wire   [31:0] buff_q0;
reg   [29:0] ap_phi_mux_phi_ln21_phi_fu_125_p4;
reg   [31:0] i_0_reg_133;
wire    ap_CS_fsm_state21;
reg   [31:0] nPartitions_0_reg_144;
reg   [31:0] solution_reg_156;
wire    ap_block_pp2_stage0;
reg   [0:0] ap_phi_mux_p_0_phi_fu_218_p4;
reg   [0:0] p_0_reg_214;
wire   [63:0] zext_ln21_fu_282_p1;
wire  signed [63:0] sext_ln63_fu_345_p1;
wire   [63:0] empty_fu_236_p1;
wire   [31:0] shl_ln21_fu_246_p2;
wire   [31:0] add_ln21_fu_251_p2;
wire   [30:0] nPartitions_fu_304_p4;
wire   [31:0] and_ln59_fu_333_p2;
wire   [31:0] sum0s_fu_368_p2;
wire   [31:0] sum1s_fu_362_p2;
reg   [23:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp2;
wire    ap_enable_pp2;

// power-on initialization
initial begin
#0 ap_CS_fsm = 24'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

PartitionCheckII_sqrt_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_SQRT_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_SQRT_DATA_WIDTH ))
PartitionCheckII_sqrt_s_axi_U(
    .AWVALID(s_axi_sqrt_AWVALID),
    .AWREADY(s_axi_sqrt_AWREADY),
    .AWADDR(s_axi_sqrt_AWADDR),
    .WVALID(s_axi_sqrt_WVALID),
    .WREADY(s_axi_sqrt_WREADY),
    .WDATA(s_axi_sqrt_WDATA),
    .WSTRB(s_axi_sqrt_WSTRB),
    .ARVALID(s_axi_sqrt_ARVALID),
    .ARREADY(s_axi_sqrt_ARREADY),
    .ARADDR(s_axi_sqrt_ARADDR),
    .RVALID(s_axi_sqrt_RVALID),
    .RREADY(s_axi_sqrt_RREADY),
    .RDATA(s_axi_sqrt_RDATA),
    .RRESP(s_axi_sqrt_RRESP),
    .BVALID(s_axi_sqrt_BVALID),
    .BREADY(s_axi_sqrt_BREADY),
    .BRESP(s_axi_sqrt_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .ap_return(ap_return),
    .array_r(array_r)
);

PartitionCheckII_output_r_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_OUTPUT_R_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_OUTPUT_R_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_OUTPUT_R_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_OUTPUT_R_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_OUTPUT_R_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_OUTPUT_R_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_OUTPUT_R_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_OUTPUT_R_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_OUTPUT_R_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_OUTPUT_R_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_OUTPUT_R_CACHE_VALUE ))
PartitionCheckII_output_r_m_axi_U(
    .AWVALID(m_axi_output_r_AWVALID),
    .AWREADY(m_axi_output_r_AWREADY),
    .AWADDR(m_axi_output_r_AWADDR),
    .AWID(m_axi_output_r_AWID),
    .AWLEN(m_axi_output_r_AWLEN),
    .AWSIZE(m_axi_output_r_AWSIZE),
    .AWBURST(m_axi_output_r_AWBURST),
    .AWLOCK(m_axi_output_r_AWLOCK),
    .AWCACHE(m_axi_output_r_AWCACHE),
    .AWPROT(m_axi_output_r_AWPROT),
    .AWQOS(m_axi_output_r_AWQOS),
    .AWREGION(m_axi_output_r_AWREGION),
    .AWUSER(m_axi_output_r_AWUSER),
    .WVALID(m_axi_output_r_WVALID),
    .WREADY(m_axi_output_r_WREADY),
    .WDATA(m_axi_output_r_WDATA),
    .WSTRB(m_axi_output_r_WSTRB),
    .WLAST(m_axi_output_r_WLAST),
    .WID(m_axi_output_r_WID),
    .WUSER(m_axi_output_r_WUSER),
    .ARVALID(m_axi_output_r_ARVALID),
    .ARREADY(m_axi_output_r_ARREADY),
    .ARADDR(m_axi_output_r_ARADDR),
    .ARID(m_axi_output_r_ARID),
    .ARLEN(m_axi_output_r_ARLEN),
    .ARSIZE(m_axi_output_r_ARSIZE),
    .ARBURST(m_axi_output_r_ARBURST),
    .ARLOCK(m_axi_output_r_ARLOCK),
    .ARCACHE(m_axi_output_r_ARCACHE),
    .ARPROT(m_axi_output_r_ARPROT),
    .ARQOS(m_axi_output_r_ARQOS),
    .ARREGION(m_axi_output_r_ARREGION),
    .ARUSER(m_axi_output_r_ARUSER),
    .RVALID(m_axi_output_r_RVALID),
    .RREADY(m_axi_output_r_RREADY),
    .RDATA(m_axi_output_r_RDATA),
    .RLAST(m_axi_output_r_RLAST),
    .RID(m_axi_output_r_RID),
    .RUSER(m_axi_output_r_RUSER),
    .RRESP(m_axi_output_r_RRESP),
    .BVALID(m_axi_output_r_BVALID),
    .BREADY(m_axi_output_r_BREADY),
    .BRESP(m_axi_output_r_BRESP),
    .BID(m_axi_output_r_BID),
    .BUSER(m_axi_output_r_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(output_r_ARVALID),
    .I_ARREADY(output_r_ARREADY),
    .I_ARADDR(output_r_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(output_r_ARLEN),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(output_r_RVALID),
    .I_RREADY(output_r_RREADY),
    .I_RDATA(output_r_RDATA),
    .I_RID(output_r_RID),
    .I_RUSER(output_r_RUSER),
    .I_RRESP(output_r_RRESP),
    .I_RLAST(output_r_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(output_r_AWREADY),
    .I_AWADDR(32'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(output_r_WREADY),
    .I_WDATA(32'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd0),
    .I_BVALID(output_r_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(output_r_BRESP),
    .I_BID(output_r_BID),
    .I_BUSER(output_r_BUSER)
);

PartitionCheckII_bkb #(
    .DataWidth( 32 ),
    .AddressRange( 100 ),
    .AddressWidth( 7 ))
buff_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(buff_address0),
    .ce0(buff_ce0),
    .we0(buff_we0),
    .d0(output_addr_read_reg_442),
    .q0(buff_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state18) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state17)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state18)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state18);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((1'b1 == ap_CS_fsm_state17)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state25) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if (((icmp_ln32_fu_323_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state25))) begin
            ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state25);
        end else if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if (((icmp_ln32_fu_323_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln57_fu_328_p2 == 1'd0))) begin
        i_0_i_reg_203 <= i_1_fu_356_p2;
    end else if (((icmp_ln32_fu_323_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        i_0_i_reg_203 <= 32'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        i_0_reg_133 <= 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state22) & (icmp_ln23_fu_287_p2 == 1'd0))) begin
        i_0_reg_133 <= i_fu_292_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln57_fu_328_p2 == 1'd0))) begin
        mask_0_i_reg_192 <= mask_fu_350_p2;
    end else if (((icmp_ln32_fu_323_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        mask_0_i_reg_192 <= 32'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        nPartitions_0_reg_144 <= 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state22) & (icmp_ln23_fu_287_p2 == 1'd0))) begin
        nPartitions_0_reg_144 <= nPartitions_2_fu_298_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln68_fu_388_p2 == 1'd1) & (icmp_ln32_reg_470 == 1'd1) & (1'b1 == ap_CS_fsm_state27))) begin
        p_0_reg_214 <= 1'd1;
    end else if (((1'b1 == ap_CS_fsm_state24) & (icmp_ln32_fu_323_p2 == 1'd0))) begin
        p_0_reg_214 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_reg_433 == 1'd0))) begin
        phi_ln21_reg_121 <= add_ln21_1_reg_437;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        phi_ln21_reg_121 <= 30'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln32_reg_470 == 1'd1) & (1'b1 == ap_CS_fsm_state27) & (icmp_ln68_fu_388_p2 == 1'd0))) begin
        solution_reg_156 <= i_2_fu_394_p2;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        solution_reg_156 <= 32'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln57_reg_474 == 1'd0))) begin
        sum0s_0_i_reg_168 <= sum0s_1_fu_374_p3;
    end else if (((icmp_ln32_fu_323_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        sum0s_0_i_reg_168 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln57_reg_474 == 1'd0))) begin
        sum1s_0_i_reg_180 <= sum1s_1_fu_381_p3;
    end else if (((icmp_ln32_fu_323_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        sum1s_0_i_reg_180 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln21_1_reg_437 <= add_ln21_1_fu_276_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        add_ln57_reg_465 <= add_ln57_fu_318_p2;
        nPartitions_1_reg_460[30 : 0] <= nPartitions_1_fu_314_p1[30 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        array1_reg_404 <= {{array_r[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln21_reg_433 <= icmp_ln21_fu_271_p2;
        icmp_ln21_reg_433_pp0_iter1_reg <= icmp_ln21_reg_433;
        phi_ln21_reg_121_pp0_iter1_reg <= phi_ln21_reg_121;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        icmp_ln32_reg_470 <= icmp_ln32_fu_323_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln57_reg_474 <= icmp_ln57_fu_328_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln57_fu_328_p2 == 1'd0))) begin
        icmp_ln59_reg_478 <= icmp_ln59_fu_339_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        lshr_ln_reg_422 <= {{add_ln21_fu_251_p2[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if (((output_r_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        n_reg_415 <= output_r_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_reg_433 == 1'd0))) begin
        output_addr_read_reg_442 <= output_r_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((output_r_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        output_addr_reg_409[29 : 0] <= empty_fu_236_p1[29 : 0];
    end
end

always @ (*) begin
    if ((icmp_ln21_fu_271_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state18 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state18 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln57_fu_328_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state25 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state25 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) & ((icmp_ln68_fu_388_p2 == 1'd1) | (icmp_ln32_reg_470 == 1'd0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln68_fu_388_p2 == 1'd1) & (icmp_ln32_reg_470 == 1'd1) & (1'b1 == ap_CS_fsm_state27))) begin
        ap_phi_mux_p_0_phi_fu_218_p4 = 1'd1;
    end else begin
        ap_phi_mux_p_0_phi_fu_218_p4 = p_0_reg_214;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_reg_433 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_phi_ln21_phi_fu_125_p4 = add_ln21_1_reg_437;
    end else begin
        ap_phi_mux_phi_ln21_phi_fu_125_p4 = phi_ln21_reg_121;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state27) & ((icmp_ln68_fu_388_p2 == 1'd1) | (icmp_ln32_reg_470 == 1'd0)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        buff_address0 = sext_ln63_fu_345_p1;
    end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        buff_address0 = zext_ln21_fu_282_p1;
    end else begin
        buff_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        buff_ce0 = 1'b1;
    end else begin
        buff_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln21_reg_433_pp0_iter1_reg == 1'd0))) begin
        buff_we0 = 1'b1;
    end else begin
        buff_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((output_r_ARREADY == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            output_r_ARADDR = output_addr_reg_409;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            output_r_ARADDR = empty_fu_236_p1;
        end else begin
            output_r_ARADDR = 'bx;
        end
    end else begin
        output_r_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((output_r_ARREADY == 1'b1)) begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            output_r_ARLEN = zext_ln21_1_fu_267_p1;
        end else if ((1'b1 == ap_CS_fsm_state2)) begin
            output_r_ARLEN = 32'd1;
        end else begin
            output_r_ARLEN = 'bx;
        end
    end else begin
        output_r_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((output_r_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11)) | ((output_r_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        output_r_ARVALID = 1'b1;
    end else begin
        output_r_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_reg_433 == 1'd0)) | ((output_r_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9)))) begin
        output_r_RREADY = 1'b1;
    end else begin
        output_r_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state2))) begin
        output_r_blk_n_AR = m_axi_output_r_ARREADY;
    end else begin
        output_r_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln21_reg_433 == 1'd0) & (1'b0 == ap_block_pp0_stage0)))) begin
        output_r_blk_n_R = m_axi_output_r_RVALID;
    end else begin
        output_r_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((output_r_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((output_r_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((output_r_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln21_fu_271_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln21_fu_271_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            if (((1'b1 == ap_CS_fsm_state22) & (icmp_ln23_fu_287_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (((icmp_ln32_fu_323_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_pp2_stage0 : begin
            if (~((1'b0 == ap_block_pp2_stage0_subdone) & (icmp_ln57_fu_328_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (icmp_ln57_fu_328_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state27 : begin
            if (((1'b1 == ap_CS_fsm_state27) & ((icmp_ln68_fu_388_p2 == 1'd1) | (icmp_ln32_reg_470 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln21_1_fu_276_p2 = (ap_phi_mux_phi_ln21_phi_fu_125_p4 + 30'd1);

assign add_ln21_fu_251_p2 = (32'd4 + shl_ln21_fu_246_p2);

assign add_ln57_fu_318_p2 = (n_reg_415 + 32'd1);

assign and_ln59_fu_333_p2 = (solution_reg_156 & mask_0_i_reg_192);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((output_r_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln21_reg_433 == 1'd0));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((output_r_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln21_reg_433 == 1'd0));
end

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state19_pp0_stage0_iter1 = ((output_r_RVALID == 1'b0) & (icmp_ln21_reg_433 == 1'd0));
end

assign ap_block_state20_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign ap_return = ap_phi_mux_p_0_phi_fu_218_p4;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_fu_236_p1 = array1_reg_404;

assign i_1_fu_356_p2 = ($signed(32'd1) + $signed(i_0_i_reg_203));

assign i_2_fu_394_p2 = (solution_reg_156 + 32'd1);

assign i_fu_292_p2 = (i_0_reg_133 + 32'd1);

assign icmp_ln21_fu_271_p2 = ((ap_phi_mux_phi_ln21_phi_fu_125_p4 == lshr_ln_reg_422) ? 1'b1 : 1'b0);

assign icmp_ln23_fu_287_p2 = ((i_0_reg_133 == n_reg_415) ? 1'b1 : 1'b0);

assign icmp_ln32_fu_323_p2 = ((solution_reg_156 < nPartitions_1_reg_460) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_328_p2 = ((i_0_i_reg_203 == add_ln57_reg_465) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_339_p2 = ((and_ln59_fu_333_p2 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_388_p2 = ((sum0s_0_i_reg_168 == sum1s_0_i_reg_180) ? 1'b1 : 1'b0);

assign mask_fu_350_p2 = mask_0_i_reg_192 << 32'd1;

assign nPartitions_1_fu_314_p1 = nPartitions_fu_304_p4;

assign nPartitions_2_fu_298_p2 = nPartitions_0_reg_144 << 32'd1;

assign nPartitions_fu_304_p4 = {{nPartitions_0_reg_144[31:1]}};

assign sext_ln63_fu_345_p1 = i_0_i_reg_203;

assign shl_ln21_fu_246_p2 = n_reg_415 << 32'd2;

assign sum0s_1_fu_374_p3 = ((icmp_ln59_reg_478[0:0] === 1'b1) ? sum0s_fu_368_p2 : sum0s_0_i_reg_168);

assign sum0s_fu_368_p2 = (buff_q0 + sum0s_0_i_reg_168);

assign sum1s_1_fu_381_p3 = ((icmp_ln59_reg_478[0:0] === 1'b1) ? sum1s_0_i_reg_180 : sum1s_fu_362_p2);

assign sum1s_fu_362_p2 = (buff_q0 + sum1s_0_i_reg_180);

assign zext_ln21_1_fu_267_p1 = lshr_ln_reg_422;

assign zext_ln21_fu_282_p1 = phi_ln21_reg_121_pp0_iter1_reg;

always @ (posedge ap_clk) begin
    output_addr_reg_409[31:30] <= 2'b00;
    nPartitions_1_reg_460[31] <= 1'b0;
end

endmodule //PartitionCheckII
