# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/AxiBurst/AxiBurst.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AxiBurst || ORIG_REF_NAME==AxiBurst} -quiet] -quiet

# IP: bd/AxiBurst/ip/AxiBurst_processing_system7_0_0/AxiBurst_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AxiBurst_processing_system7_0_0 || ORIG_REF_NAME==AxiBurst_processing_system7_0_0} -quiet] -quiet

# IP: bd/AxiBurst/ip/AxiBurst_AxiBurst_0_10/AxiBurst_AxiBurst_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AxiBurst_AxiBurst_0_10 || ORIG_REF_NAME==AxiBurst_AxiBurst_0_10} -quiet] -quiet

# IP: bd/AxiBurst/ip/AxiBurst_ps7_0_axi_periph_9/AxiBurst_ps7_0_axi_periph_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AxiBurst_ps7_0_axi_periph_9 || ORIG_REF_NAME==AxiBurst_ps7_0_axi_periph_9} -quiet] -quiet

# IP: bd/AxiBurst/ip/AxiBurst_rst_ps7_0_50M_9/AxiBurst_rst_ps7_0_50M_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AxiBurst_rst_ps7_0_50M_9 || ORIG_REF_NAME==AxiBurst_rst_ps7_0_50M_9} -quiet] -quiet

# IP: bd/AxiBurst/ip/AxiBurst_axi_mem_intercon_9/AxiBurst_axi_mem_intercon_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AxiBurst_axi_mem_intercon_9 || ORIG_REF_NAME==AxiBurst_axi_mem_intercon_9} -quiet] -quiet

# IP: bd/AxiBurst/ip/AxiBurst_auto_pc_4/AxiBurst_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AxiBurst_auto_pc_4 || ORIG_REF_NAME==AxiBurst_auto_pc_4} -quiet] -quiet

# IP: bd/AxiBurst/ip/AxiBurst_auto_pc_5/AxiBurst_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AxiBurst_auto_pc_5 || ORIG_REF_NAME==AxiBurst_auto_pc_5} -quiet] -quiet

# IP: bd/AxiBurst/ip/AxiBurst_auto_us_2/AxiBurst_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==AxiBurst_auto_us_2 || ORIG_REF_NAME==AxiBurst_auto_us_2} -quiet] -quiet

# XDC: bd/AxiBurst/AxiBurst_ooc.xdc
